converted travis CI to GHA CI
plus3it/terraform-aws-tardigrade-cloudtrail pull request #157
Opened 2023-01-31 19:02 UTC by johnricords

2023-02-01 00:49 UTC, lorengordon requested changes

2023-02-01 00:49 UTC, lorengordon commented on .github/workflows/release.yml
> +      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
This will need to skip the mockstack test...

```suggestion
  release:
    uses: plus3it/actions-workflows/.github/workflows/release.yml@41056300ba78d8be98b45f057aea246f8c4f30cf
    with:
      mockstacktest-enable: false
    secrets:
      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
```

2023-02-09 18:35 UTC, johnricords commented on .github/workflows/release.yml
> +      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
mockstack is still failing; rather than "skipping" the job

2023-02-13 14:42 UTC, lorengordon submitted a review, later dismissed

2023-02-13 16:02 UTC, lorengordon approved these changes
🚢

2023-02-13 16:02 UTC, lorengordon commented
@johnricords Approved, feel free to merge

2023-02-13 18:22 UTC, merged