Removes create variable from module
plus3it/terraform-aws-tardigrade-cloudtrail pull request #97
Opened 2021-01-04 21:47 UTC by eemperor

2021-01-04 21:49 UTC, eemperor commented
Result of `make test`:

```
PASS
ok      tardigarde-ci/tests     179.339s
[terratest/test]: Completed successfully!
```

2021-01-04 22:28 UTC, lorengordon requested changes
This works, but there is a bit of extra cleanup we can do with the syntax, now that the cloudtrail is not optional. Left a couple comments, but all the outputs with the `join(...)` syntax can also be simplified. E.g...

```
output "cloudtrail_id" {
  description = "The name of the trail"
  value       = aws_cloudtrail.this.id
}
```

2021-01-04 22:28 UTC, lorengordon commented on outputs.tf
> +  value       = length(aws_cloudtrail.this) > 0 ? aws_cloudtrail.this.kms_key_id : null
Since `aws_cloudtrail.this` is no longer optional, this whole construct can be simplifed:

```suggestion
  value       = aws_cloudtrail.this.kms_key_id
```

2021-01-04 22:28 UTC, lorengordon commented on versions.tf
> +  required_version = ">= 0.13"
We aren't actually using any 0.13 features here, so this can stay 0.12.

```suggestion
  required_version = ">= 0.12"
```

2021-01-05 14:49 UTC, eemperor commented on outputs.tf
> +  value       = length(aws_cloudtrail.this) > 0 ? aws_cloudtrail.this.kms_key_id : null
Ah yes.  Good call.

2021-01-05 14:50 UTC, eemperor commented on versions.tf
> +  required_version = ">= 0.13"
Okay.  Will undo the change.

2021-01-05 15:04 UTC, eemperor commented
Result of `make test` after updates:

```
PASS
ok      tardigarde-ci/tests     169.663s
[terratest/test]: Completed successfully!
```

2021-01-05 15:14 UTC, lorengordon commented on outputs.tf
> +  value       = aws_cloudwatch_log_group.this
This resource is still optional, so this actually changes the output format. Instead of the returning the object (e.g. `{...}`), it returns a list(object) (e.g. `[{...}]`). But we should change the condition to match the condition used by the resource...

```suggestion
  value       = local.create_log_group ? aws_cloudwatch_log_group.this[0] : null
```

2021-01-05 17:47 UTC, lorengordon approved these changes
🚢

2021-01-05 18:18 UTC, merged